[project]
name = "translationtools"
version = "0.1.0"
description = "Translation tools"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
]
